all:
	gcc -Iinclude -I"C:/Users/PC/Desktop/freeglut-3.6.0/build/include" src/*.c -L. -lfreeglut -lSOIL -lglu32 -lopengl32 -lm -o beadando.exe

linux:
	gcc -Iinclude src/*.c -lSOIL -lGL -lGLU -lglut -lm -o beadando
